Gym_System-main/ecommerse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from ecommerse import settings

urlpatterns = [
    path('clientes/', include('modulos.clientes.urls')),
    path('mensualidad/', include('modulos.mensualidad.urls')),
    path('maquinaria/', include('modulos.maquinaria.urls')),
    path('instrumentos/', include('modulos.instrumentos.urls')),
    path('finanzas/', include('modulos.finanzas.urls')),
    path('', include('modulos.login.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ecommerse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from ecommerse import settings

urlpatterns = [
    path('clientes/', include('modulos.clientes.urls')),
    path('mensualidad/', include('modulos.mensualidad.urls')),
    path('maquinaria/', include('modulos.maquinaria.urls')),
    path('instrumentos/', include('modulos.instrumentos.urls')),
    path('finanzas/', include('modulos.finanzas.urls')),
    path('', include('modulos.login.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

modulos/clientes/urls.py
from django.urls import path
from modulos.clientes.views.cliente.views import *


app_name = "clientes"
urlpatterns = [
    path('detalle_cliente/', (DetalleCliente.as_view()), name='detalle_cliente'),
    path('crear_cliente/', (Addcliente.as_view()), name='crear_cliente'),
    path('editar_cliente/<int:pk>', (EditarCliente.as_view()), name='editar_cliente'),
    path('eliminar_cliente/<int:pk>', (EliminarCliente.as_view()), name='eliminar_cliente'),

]

modulos/finanzas/urls.py
from django.urls import path
from modulos.finanzas.views.finanzas.views import *


app_name = "finanzas"
urlpatterns = [
    path('detalle_finanzas/', (DetalleFinanzas.as_view()), name='detalle_finanzas'),
    path('crear_finanzas/', (RellenarFinanza.as_view()), name='crear_finanzas'),
    path('editar_finanzas/<int:pk>', (EditarFinanzas.as_view()), name='editar_finanzas'),
    path('eliminar_finanzas/<int:pk>', (EliminarFinanzas.as_view()), name='eliminar_finanzas'),

]

modulos/maquinaria/urls.py
from django.urls import path
from modulos.maquinaria.views.maquinaria.views import *

app_name = "maquinaria"
urlpatterns = [
    path('detalle_maquinaria/', (maquinariaListView.as_view()), name='detalle_maquinaria'),
    path('crear_maquinaria/', (CrearMaquinaria.as_view()), name='crear_maquinaria'),
    path('editar_maquinaria/<int:pk>', (ActualizarMaquinaria.as_view()), name='editar_maquinaria'),
    path('eliminar_maquinaria/<int:pk>', (EliminarMaquinaria.as_view()), name='eliminar_maquinaria'),

]

modulos/mensualidad/urls.py
from django.urls import path
from modulos.mensualidad.views.mensualidad.views import *


app_name = "mensualidad"
urlpatterns = [
    path('detalle_mensualidad/',(detalleMensualidad.as_view()), name='detalle_mensualidad'),
    path('crear_mensualidad/',(CrearMensualidad.as_view()), name='crear_mensualidad'),
    path('editar_mensualidad/<int:pk>',(ActualizarMensualidad.as_view()), name='editar_mensualidad'),
    path('eliminar_mensualidad/<int:pk>',(EliminarMensualidad.as_view()), name='eliminar_mensualidad'),

]

templates/barlateral_mod_plantilla.html
{% extends 'index.html' %}
{% load static %}
{% block main %}

    <div class="navegacion">
        <div class="enlaces">
            <nav>
                <a href="{% url 'clientes:detalle_cliente' %}"> Clientes </a>
                <a href="{% url 'maquinaria:detalle_maquinaria' %}"> Maquinaria </a>
                <a href="{% url 'instrumentos:detalle_instrumento' %}"> Instrumentos </a>
                <a href="{% url 'mensualidad:detalle_mensualidad' %}"> Mensualidad </a>
                <a href="{% url 'finanzas:detalle_finanzas' %}"> Finanzas </a>
            </nav>
        </div>

        <div class="container">
            <div class="diseño-tabla  mt-md-5 me-md-5">

                {% block contenido %}

                {% endblock %}

                {% block pagination %}
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-center mt-5">

                            {% if page_obj.has_previous %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a>
                                </li>
                            {% endif %}

                            {% for i in page_obj.paginator.page_range %}
                                {% if i == page_obj.number %}
                                    <li class="page-item active">
                                        <a class="page-link" href="#">{{ i }}</a>
                                    </li>
                                {% else %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                                    </li>
                                {% endif %}
                            {% endfor %}

                            {% if page_obj.has_next %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                {% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

templates/formulario_plantilla.html
{% extends 'index.html' %}
{% load static %}

{% block main %}
    <form class="container text-dark" method="POST" action="{{ action_save }}" id="formulario"
          enctype="multipart/form-data">
        {% csrf_token %}
        <div class="card formul card-primary">
            <div class="card-header bg-black">
                <h3 class="card-title text-center text-white">
                    {{ titulo }}
                </h3>
            </div>
            <div class="card-body row g-3">

                {% block formulario %}

                {% endblock %}
            </div>

        </div>
        {% block boton %}
            <div class="botones-form mt-3">
                <div>
                    <button type="submit" class="btn btn-primary" id="boton-guardar">
                        Guardar registro
                    </button>
                </div>
                <div>
                    <a href="{{ url_anterior }}" class="btn btn-danger">
                        Cancelar
                    </a>
                </div>
            </div>
        {% endblock %}
        </div>


    </form>


{% endblock %}

templates/index.html
<!doctype html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/estilo.css' %}">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'css/tooltips.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.2.0/fonts/remixicon.css" rel="stylesheet">
    <link rel="icon" href="{% static 'img/icon.ico' %}" type="png" sizes="32x32">
    {% block java %}
    {% endblock %}

    {% block title %}
        <title> Labyrinth D.S </title>
    {% endblock %}
</head>

   <header>
    {% block header %}
        {% include 'navbar.html' %}
    {% endblock %}
    </header>
<body>
{% block main %}
    <div class="contenedor-iconos">
        <div class="contenido">
            <a class="text-decoration-none" href="{% url 'clientes:detalle_cliente' %}">
                <img src=" {% static 'img/Clientes.png' %} " alt="Icono de Clientes">
            </a>
            <span class="tooltip-infor"> Módulo para registro de clientes nuevos </span>
        </div>

        <div class="contenido" title="Maquinaria">
            <a class="text-decoration-none" href="{% url 'maquinaria:detalle_maquinaria' %}">
                <img src=" {% static 'img/Maquinarias.png' %} " alt="Icono de Maquinaria">
                <span class="tooltip-infor"> Módulo para registrar maquinaria </span>
            </a>
        </div>

        <div class="contenido">
            <a class="text-decoration-none" href="{% url 'instrumentos:detalle_instrumento' %}">
                <img src=" {% static 'img/Instrumentos.png' %} " alt="Icono de Instrumentos">
                <span class="tooltip-infor"> Módulo para registrar instrumentos </span>
            </a>

        </div>
        <div class="contenido">
            <a class="text-decoration-none" href="{% url 'mensualidad:detalle_mensualidad' %}">
                <img src=" {% static 'img/Mensualidad.png' %} " alt="Icono de Mensualidad">
                <span class="tooltip-infor"> Módulo para asignación de mensualidades a los clientes </span>
            </a>
        </div>
        <div class="contenido">
            <a class="text-decoration-none" href="{% url 'finanzas:detalle_finanzas' %}">
                <img src=" {% static 'img/Finanzas.png' %} " alt="Icono de Finanzas">
                <span class="tooltip-infor"> Módulo que permitirá llevar un control sobre la contabilidad del gimnasio </span>
            </a>
        </div>

    </div>

{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>

{% block js %}

{% endblock %}
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-dark bg-black fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="/"> Labyrinth D.S </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar"
                aria-controls="offcanvasDarkNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar"
             aria-labelledby="offcanvasDarkNavbarLabel">
            <div class="offcanvas-header">
                <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel"> Labyrinth D.S </h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas"
                        aria-label="Close">
                </button>
            </div>
            <div class="offcanvas-body">
                <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                    <span class="nav-text">
                      <a class="nav-link" href="{% url 'logout' %}">Cerrar Sesión</a>
                    </span>
                </ul>
            </div>
        </div>
    </div>
</nav>