Gym_System-main/ecommerse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from ecommerse import settings

urlpatterns = [
    path('clientes/', include('modulos.clientes.urls')),
    path('mensualidad/', include('modulos.mensualidad.urls')),
    path('maquinaria/', include('modulos.maquinaria.urls')),
    path('instrumentos/', include('modulos.instrumentos.urls')),
    path('finanzas/', include('modulos.finanzas.urls')),
    path('', include('modulos.login.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Gym_System-main/modulos/mensualidad/urls.py
from django.urls import path
from modulos.mensualidad.views.mensualidad.views import *


app_name = "mensualidad"
urlpatterns = [
    path('detalle_mensualidad/',(detalleMensualidad.as_view()), name='detalle_mensualidad'),
    path('crear_mensualidad/',(CrearMensualidad.as_view()), name='crear_mensualidad'),
    path('editar_mensualidad/<int:pk>',(ActualizarMensualidad.as_view()), name='editar_mensualidad'),
    path('eliminar_mensualidad/<int:pk>',(EliminarMensualidad.as_view()), name='eliminar_mensualidad'),

]

ecommerse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from ecommerse import settings

urlpatterns = [
    path('clientes/', include('modulos.clientes.urls')),
    path('mensualidad/', include('modulos.mensualidad.urls')),
    path('maquinaria/', include('modulos.maquinaria.urls')),
    path('instrumentos/', include('modulos.instrumentos.urls')),
    path('finanzas/', include('modulos.finanzas.urls')),
    path('', include('modulos.login.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

modulos/mensualidad/urls.py
from django.urls import path
from modulos.mensualidad.views.mensualidad.views import *


app_name = "mensualidad"
urlpatterns = [
    path('detalle_mensualidad/',(detalleMensualidad.as_view()), name='detalle_mensualidad'),
    path('crear_mensualidad/',(CrearMensualidad.as_view()), name='crear_mensualidad'),
    path('editar_mensualidad/<int:pk>',(ActualizarMensualidad.as_view()), name='editar_mensualidad'),
    path('eliminar_mensualidad/<int:pk>',(EliminarMensualidad.as_view()), name='eliminar_mensualidad'),

]

Gym_System-main/modulos/mensualidad/models.py
from django.db import models
from django.utils import timezone
from modulos.clientes.models import *
from django.utils.timezone import now
# Create your models here.



class Mensualidad(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.PROTECT)
    precio = models.DecimalField(default='', max_digits=9, decimal_places=2, verbose_name='Pago')
    fecha_inicio = models.DateField(default=now)
    fecha_finalizacion= models.DateField(default=None)

    def __str__(self):
        return "{}".format(self.cliente)

    class Meta:
        verbose_name = "Mensualidad"
        verbose_name_plural = "Mensualidades"
        ordering = ('cliente',)

modulos/mensualidad/models.py
from django.db import models
from django.utils import timezone
from modulos.clientes.models import *
from django.utils.timezone import now
# Create your models here.



class Mensualidad(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.PROTECT)
    precio = models.DecimalField(default='', max_digits=9, decimal_places=2, verbose_name='Pago')
    fecha_inicio = models.DateField(default=now)
    fecha_finalizacion= models.DateField(default=None)

    def __str__(self):
        return "{}".format(self.cliente)

    class Meta:
        verbose_name = "Mensualidad"
        verbose_name_plural = "Mensualidades"
        ordering = ('cliente',)

Gym_System-main/modulos/mensualidad/forms.py
from django.db import models
from django import forms
from django.utils import timezone
from django.forms import ModelForm
from modulos.mensualidad.models import *

class CabeceraMensual(ModelForm):
    class Meta:
        model = Mensualidad
        fields = '__all__'
        widgets = {
            'cliente': forms.Select(attrs={'class': 'form-control '}),
            'precio': forms.NumberInput(attrs={'class': 'form-control'}),
            'fecha_inicio': forms.DateInput(format=('%Y-%m-%d'),attrs={'class': 'form-control', 'type': 'date', 'id':'fecha'}),
            'fecha_finalizacion': forms.DateInput(
                         format=('%Y-%m-%d'),
                         attrs={'class': 'form-control', 'id' : 'fecha_final'})
        }

modulos/mensualidad/forms.py
from django.db import models
from django import forms
from django.utils import timezone
from django.forms import ModelForm
from modulos.mensualidad.models import *

class CabeceraMensual(ModelForm):
    class Meta:
        model = Mensualidad
        fields = '__all__'
        widgets = {
            'cliente': forms.Select(attrs={'class': 'form-control '}),
            'precio': forms.NumberInput(attrs={'class': 'form-control'}),
            'fecha_inicio': forms.DateInput(format=('%Y-%m-%d'),attrs={'class': 'form-control', 'type': 'date', 'id':'fecha'}),
            'fecha_finalizacion': forms.DateInput(
                         format=('%Y-%m-%d'),
                         attrs={'class': 'form-control', 'id' : 'fecha_final'})
        }

Gym_System-main/modulos/mensualidad/views/mensualidad/views.py
from django.urls import reverse_lazy

from modulos.mensualidad.models import *
from django.views.generic import *
from modulos.mensualidad.forms import *
from django.contrib.auth.mixins import LoginRequiredMixin

class detalleMensualidad(LoginRequiredMixin, ListView):
    template_name = 'detalleMensualidad.html'
    context_object_name = 'mensualidad'
    model = Mensualidad
    paginate_by = 5

    def get_queryset(self):
        query = self.request.GET.get("query")
        print(query)
        if query:
            return self.model.objects.filter(cliente__nombre__icontains=query)
        else:
            return self.model.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['url_anterior'] = "/"
        context['listar_url'] = '/mensualidad/menu/'
        context['titulo'] = 'Registro de Mensualidad'
        context['query'] = self.request.GET.get("query") or ""
        return context


class CrearMensualidad(LoginRequiredMixin, CreateView):
    model = Mensualidad
    template_name = 'Crear_mensu.html'
    form_class = CabeceraMensual
    success_url = reverse_lazy('mensualidad:detalle_mensualidad')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Crear Mensualidad'
        context['action_save'] = self.request.path
        context['url_anterior'] = '/mensualidad/detalle_mensualidad/'
        context['listar_url'] = '/mensualidad/detalle_mensualidad/'

        return context


# Eliminar
class EliminarMensualidad(LoginRequiredMixin, DeleteView):
    model = Mensualidad
    template_name = 'eliminar_mensu.html'
    success_url = reverse_lazy('mensualidad:detalle_mensualidad')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action_save'] = self.request.path
        context['titulo'] = 'Eliminar Registro de Mensualidad'
        context['url_anterior'] = '/mensualidad/detalle_mensualidad/'
        context['listar_url'] = '/mensualidad/detalle_mensualidad/'
        return context


# Actualizar
class ActualizarMensualidad(LoginRequiredMixin, UpdateView):
    model = Mensualidad
    template_name = 'editar_mensu.html'
    success_url = reverse_lazy('mensualidad:detalle_mensualidad')
    form_class = CabeceraMensual

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action_save'] = self.request.path
        context['titulo'] = 'Actualizar Datos de la mensualidad'
        context['url_anterior'] = '/mensualidad/detalle_mensualidad/'
        context['listar_url'] = '/mensualidad/detalle_mensualidad/'
        return context

modulos/mensualidad/views/mensualidad/views.py
from django.urls import reverse_lazy

from modulos.mensualidad.models import *
from django.views.generic import *
from modulos.mensualidad.forms import *
from django.contrib.auth.mixins import LoginRequiredMixin

class detalleMensualidad(LoginRequiredMixin, ListView):
    template_name = 'detalleMensualidad.html'
    context_object_name = 'mensualidad'
    model = Mensualidad
    paginate_by = 5

    def get_queryset(self):
        query = self.request.GET.get("query")
        print(query)
        if query:
            return self.model.objects.filter(cliente__nombre__icontains=query)
        else:
            return self.model.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['url_anterior'] = "/"
        context['listar_url'] = '/mensualidad/menu/'
        context['titulo'] = 'Registro de Mensualidad'
        context['query'] = self.request.GET.get("query") or ""
        return context


class CrearMensualidad(LoginRequiredMixin, CreateView):
    model = Mensualidad
    template_name = 'Crear_mensu.html'
    form_class = CabeceraMensual
    success_url = reverse_lazy('mensualidad:detalle_mensualidad')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Crear Mensualidad'
        context['action_save'] = self.request.path
        context['url_anterior'] = '/mensualidad/detalle_mensualidad/'
        context['listar_url'] = '/mensualidad/detalle_mensualidad/'

        return context


# Eliminar
class EliminarMensualidad(LoginRequiredMixin, DeleteView):
    model = Mensualidad
    template_name = 'eliminar_mensu.html'
    success_url = reverse_lazy('mensualidad:detalle_mensualidad')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action_save'] = self.request.path
        context['titulo'] = 'Eliminar Registro de Mensualidad'
        context['url_anterior'] = '/mensualidad/detalle_mensualidad/'
        context['listar_url'] = '/mensualidad/detalle_mensualidad/'
        return context


# Actualizar
class ActualizarMensualidad(LoginRequiredMixin, UpdateView):
    model = Mensualidad
    template_name = 'editar_mensu.html'
    success_url = reverse_lazy('mensualidad:detalle_mensualidad')
    form_class = CabeceraMensual

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action_save'] = self.request.path
        context['titulo'] = 'Actualizar Datos de la mensualidad'
        context['url_anterior'] = '/mensualidad/detalle_mensualidad/'
        context['listar_url'] = '/mensualidad/detalle_mensualidad/'
        return context

Gym_System-main/modulos/mensualidad/templates/Crear_mensu.html
{% extends 'formulario_plantilla.html' %}
{% load static %}


{% block formulario %}
    {% if form.errors %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>Error al Grabar</strong> {{ form.errors }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}

    <div>
        <h5>Seleccione el cliente ingresado</h5>
        {{ form.cliente }}
    </div>
    <br>
    <div>
        <h5>Pago</h5>
        {{ form.precio }}
    </div>
    <br>
    <div>
        <h5>Fecha de inicio</h5>
        {{ form.fecha_inicio }}
    </div>
    <br>
    <div>
        <h5>Fecha de finalizacion</h5>
        {{ form.fecha_finalizacion }}
    </div>
    <br>

{% endblock %}
{% block js %}
    <script src="{% static 'js/peticiones.js' %}"></script>

    <script>
        window.addEventListener('load', siguienteMes);

        document.getElementById('fecha').addEventListener('change', siguienteMes);

        function siguienteMes() {
            let fechaInicio = new Date(document.getElementById("fecha").value);
            fechaInicio.setDate(fechaInicio.getDate() + 1);
            fechaInicio.setMonth(fechaInicio.getMonth() + 1);
            document.getElementById("fecha_final").value = fechaInicio.toLocaleDateString();
        }
    </script>
{% endblock %}

Gym_System-main/modulos/mensualidad/templates/detalleMensualidad.html
{% extends 'barlateral_mod_plantilla.html' %}
{% load static %}

{% block title %}
    <title> Mensualidad </title>
{% endblock %}

{% block contenido %}

    {% block search %}
        <form action="{% url 'mensualidad:detalle_mensualidad' %}" method="GET">
            <div class="input-group mb-3">
                <input type="text" name="query" value="{{ query }}" class="form-control"
                       placeholder="Buscar cliente por nombre" id="idInputSearch"
                       aria-describedby="basic-addon2"/>
                <button type="submit" class="btn btn-primary mr-1" id="idSearchSp">
                    Buscar
                </button>
            </div>
        </form>
    {% endblock %}

    <table class="container table table-responsive">
        <thead>
        <tr>
            <th> Cliente</th>
            <th> Precio</th>
            <th> fecha_inicio</th>
            <th> fecha_finalizacion</th>
            <th> Estado</th>
            <th> Acciones</th>
        </tr>
        </thead>
        <tbody>
        {% for objects in mensualidad %}
            <tr>

                <td>{{ objects.cliente }}</td>
                <td>{{ objects.precio }}</td>
                <td>{{ objects.fecha_inicio }}</td>
                <td>{{ objects.fecha_finalizacion }}</td>
                <td>
                    {% if  objects.precio == 25 %}
                        Pagado
                    {% elif objects.precio <= 24 %}
                        Pendiente
                    {% endif %}
                </td>
                <td>
                    <div class="btn-accion">
                        <div>
                            <a class="text-decoration-none"
                               href="{% url 'mensualidad:editar_mensualidad' objects.id %}">
                                <i class="ri-edit-2-line text-dark"></i>
                            </a>
                        </div>
                        <div>
                            <a class="text-decoration-none"
                               href="{% url 'mensualidad:eliminar_mensualidad' objects.id %}">
                                <i class="ri-eraser-line text-dark"></i>
                            </a>
                        </div>
                    </div>
                </td>

            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="btn-add">
        <a href="{% url 'mensualidad:crear_mensualidad' %}" class="btn btn-success btn-lg mt-md-5 me-md-auto ms-md-3">
            Asignar Mensualidad
        </a>
    </div>
{% endblock %}

Gym_System-main/modulos/mensualidad/templates/editar_mensu.html
{% extends 'formulario_plantilla.html' %}
{% load static %}


{% block formulario %}
    {% csrf_token %}
    {% if form.errors %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>Error al Grabar</strong> {{ form.errors }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}

    <input type="hidden" name="action" value="{{ action }}">
    {{ form.as_p }}

    <output id="idImgContenedor" style="width: 200px !important;"></output>

{% endblock %}

Gym_System-main/modulos/mensualidad/templates/eliminar_mensu.html
{% extends 'formulario_plantilla.html' %}
{% load static %}


{% block formulario %}
    {% csrf_token %}
    <h3 style='text-align: center'>¿Estás seguro de eliminar el registro de "{{ object }}"?</h3>
{% endblock %}