Gym_System-main/ecommerse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from ecommerse import settings

urlpatterns = [
    path('clientes/', include('modulos.clientes.urls')),
    path('mensualidad/', include('modulos.mensualidad.urls')),
    path('maquinaria/', include('modulos.maquinaria.urls')),
    path('instrumentos/', include('modulos.instrumentos.urls')),
    path('finanzas/', include('modulos.finanzas.urls')),
    path('', include('modulos.login.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Gym_System-main/modulos/maquinaria/urls.py
from django.urls import path
from modulos.maquinaria.views.maquinaria.views import *

app_name = "maquinaria"
urlpatterns = [
    path('detalle_maquinaria/', (maquinariaListView.as_view()), name='detalle_maquinaria'),
    path('crear_maquinaria/', (CrearMaquinaria.as_view()), name='crear_maquinaria'),
    path('editar_maquinaria/<int:pk>', (ActualizarMaquinaria.as_view()), name='editar_maquinaria'),
    path('eliminar_maquinaria/<int:pk>', (EliminarMaquinaria.as_view()), name='eliminar_maquinaria'),

]

ecommerse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from ecommerse import settings

urlpatterns = [
    path('clientes/', include('modulos.clientes.urls')),
    path('mensualidad/', include('modulos.mensualidad.urls')),
    path('maquinaria/', include('modulos.maquinaria.urls')),
    path('instrumentos/', include('modulos.instrumentos.urls')),
    path('finanzas/', include('modulos.finanzas.urls')),
    path('', include('modulos.login.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

modulos/maquinaria/urls.py
from django.urls import path
from modulos.maquinaria.views.maquinaria.views import *

app_name = "maquinaria"
urlpatterns = [
    path('detalle_maquinaria/', (maquinariaListView.as_view()), name='detalle_maquinaria'),
    path('crear_maquinaria/', (CrearMaquinaria.as_view()), name='crear_maquinaria'),
    path('editar_maquinaria/<int:pk>', (ActualizarMaquinaria.as_view()), name='editar_maquinaria'),
    path('eliminar_maquinaria/<int:pk>', (EliminarMaquinaria.as_view()), name='eliminar_maquinaria'),

]

Gym_System-main/modulos/maquinaria/models.py
from django.db import models
from django.utils.timezone import now


class Maquinaria(models.Model):
    Descripcion = models.CharField(max_length=130, unique=True)
    Cantidad = models.IntegerField(default='')
    precio_maquinaria = models.IntegerField(default=0)
    fecha_compra_maquinaria = models.DateField(default=now)
    Mantenimiento = models.BooleanField(default=False)


    def __str__(self):
        return "{}".format(self.Descripcion)

    class Meta:
        ordering = ('Descripcion',)

modulos/maquinaria/models.py
from django.db import models
from django.utils.timezone import now


class Maquinaria(models.Model):
    Descripcion = models.CharField(max_length=130, unique=True)
    Cantidad = models.IntegerField(default='')
    precio_maquinaria = models.IntegerField(default=0)
    fecha_compra_maquinaria = models.DateField(default=now)
    Mantenimiento = models.BooleanField(default=False)


    def __str__(self):
        return "{}".format(self.Descripcion)

    class Meta:
        ordering = ('Descripcion',)

Gym_System-main/modulos/maquinaria/forms.py
from django import forms
from django.forms import ModelForm
from modulos.maquinaria.models import *

class MaquinariaForm(ModelForm):
    class Meta:
        model = Maquinaria
        fields = '__all__'
        exclude=['usuario']

        widgets = {
            'Descripcion': forms.TextInput(attrs={'class': 'form-control','placeholder':'Ingrese nombre de la Maquina'}),
            'Cantidad': forms.TextInput(attrs={'class': 'form-control','placeholder':'Ingrese la Cantidad'}),
            'precio_maquinaria': forms.NumberInput(attrs={'class': 'form-control','placeholder':'Ingrese precio de la maquinaria'}),
            'fecha_compra_maquinaria': forms.DateInput(format=('%Y-%m-%d'),
                                                       attrs={'class': 'form-control', 'type': 'date', 'id':'fecha'}),
            'Mantenimiento': forms.CheckboxInput()
        }

modulos/maquinaria/forms.py
from django import forms
from django.forms import ModelForm
from modulos.maquinaria.models import *

class MaquinariaForm(ModelForm):
    class Meta:
        model = Maquinaria
        fields = '__all__'
        exclude=['usuario']

        widgets = {
            'Descripcion': forms.TextInput(attrs={'class': 'form-control','placeholder':'Ingrese nombre de la Maquina'}),
            'Cantidad': forms.TextInput(attrs={'class': 'form-control','placeholder':'Ingrese la Cantidad'}),
            'precio_maquinaria': forms.NumberInput(attrs={'class': 'form-control','placeholder':'Ingrese precio de la maquinaria'}),
            'fecha_compra_maquinaria': forms.DateInput(format=('%Y-%m-%d'),
                                                       attrs={'class': 'form-control', 'type': 'date', 'id':'fecha'}),
            'Mantenimiento': forms.CheckboxInput()
        }

Gym_System-main/modulos/maquinaria/views/maquinaria/views.py
from django.urls import reverse_lazy
from django.views.generic import *
from modulos.maquinaria.models import *
from modulos.maquinaria.forms import *
from django.contrib.auth.mixins import LoginRequiredMixin
class maquinariaListView(LoginRequiredMixin, ListView):
    template_name = "maquinaria/detalle_maquinaria.html"
    model = Maquinaria
    context_object_name = 'maquinaria'
    paginate_by = 5

    def get_queryset(self):
        query = self.request.GET.get("query")
        print(query)
        if query:
            return self.model.objects.filter(Descripcion__icontains=query)
        else:
            return self.model.objects.all()
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['crear_url'] = 'crearmaquinaria/'
        mant = context['maquinaria']
        estados = ['Bajo Mantenimiento' if s.Mantenimiento else 'Disponible' for s in mant]
        context['estado_guardado'] = zip(mant, estados)
        context['query'] = self.request.GET.get("query") or ""
        return context

class CrearMaquinaria(LoginRequiredMixin, CreateView):
    model = Maquinaria
    template_name = "maquinaria/añadir_maquinaria.html"
    success_url = reverse_lazy('maquinaria:detalle_maquinaria')
    form_class = MaquinariaForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Añadir Maquinaria'
        context['url_anterior'] = '/maquinaria/detalle_maquinaria/'
        context['listar_url'] = '/maquinaria/detalle_maquinaria/'
        return context

class ActualizarMaquinaria(LoginRequiredMixin, UpdateView):
    model = Maquinaria
    template_name = "maquinaria/editar_maquinaria.html"
    success_url = reverse_lazy('maquinaria:detalle_maquinaria')
    form_class = MaquinariaForm


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action_save'] = self.request.path
        context['titulo'] = 'Editar Maquinaria'
        context['url_anterior'] = '/maquinaria/detalle_maquinaria/'
        return context

class EliminarMaquinaria(LoginRequiredMixin, DeleteView):
    model = Maquinaria
    template_name = "maquinaria/eliminar_maquinaria.html"
    success_url = reverse_lazy('maquinaria:detalle_maquinaria')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action_save'] = self.request.path
        context['titulo'] = 'Eliminar Maquinaria'
        context['url_anterior'] = '/maquinaria/detalle_maquinaria/'
        return context

modulos/maquinaria/views/maquinaria/views.py
from django.urls import reverse_lazy
from django.views.generic import *
from modulos.maquinaria.models import *
from modulos.maquinaria.forms import *
from django.contrib.auth.mixins import LoginRequiredMixin
class maquinariaListView(LoginRequiredMixin, ListView):
    template_name = "maquinaria/detalle_maquinaria.html"
    model = Maquinaria
    context_object_name = 'maquinaria'
    paginate_by = 5

    def get_queryset(self):
        query = self.request.GET.get("query")
        print(query)
        if query:
            return self.model.objects.filter(Descripcion__icontains=query)
        else:
            return self.model.objects.all()
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['crear_url'] = 'crearmaquinaria/'
        mant = context['maquinaria']
        estados = ['Bajo Mantenimiento' if s.Mantenimiento else 'Disponible' for s in mant]
        context['estado_guardado'] = zip(mant, estados)
        context['query'] = self.request.GET.get("query") or ""
        return context

class CrearMaquinaria(LoginRequiredMixin, CreateView):
    model = Maquinaria
    template_name = "maquinaria/añadir_maquinaria.html"
    success_url = reverse_lazy('maquinaria:detalle_maquinaria')
    form_class = MaquinariaForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Añadir Maquinaria'
        context['url_anterior'] = '/maquinaria/detalle_maquinaria/'
        context['listar_url'] = '/maquinaria/detalle_maquinaria/'
        return context

class ActualizarMaquinaria(LoginRequiredMixin, UpdateView):
    model = Maquinaria
    template_name = "maquinaria/editar_maquinaria.html"
    success_url = reverse_lazy('maquinaria:detalle_maquinaria')
    form_class = MaquinariaForm


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action_save'] = self.request.path
        context['titulo'] = 'Editar Maquinaria'
        context['url_anterior'] = '/maquinaria/detalle_maquinaria/'
        return context

class EliminarMaquinaria(LoginRequiredMixin, DeleteView):
    model = Maquinaria
    template_name = "maquinaria/eliminar_maquinaria.html"
    success_url = reverse_lazy('maquinaria:detalle_maquinaria')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action_save'] = self.request.path
        context['titulo'] = 'Eliminar Maquinaria'
        context['url_anterior'] = '/maquinaria/detalle_maquinaria/'
        return context

modulos/maquinaria/templates/maquinaria/añadir_maquinaria.html
{% extends 'formulario_plantilla.html' %}
{% load static %}
{% block title %}
    <title> Registro de Maquinaria </title>
{% endblock %}


{% block formulario %}
    {% if form.errors %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>Error al Grabar</strong> {{ form.errors }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}

    {{ form.as_p }}

{% endblock %}

modulos/maquinaria/templates/maquinaria/detalle_maquinaria.html
{% extends 'barlateral_mod_plantilla.html' %}
{% load static %}

{% block title %}
    <title> Maquinaria </title>
{% endblock %}

{% block contenido %}
    {% block search %}
        <form action="{% url 'maquinaria:detalle_maquinaria' %}" method="GET">
            <div class="input-group mb-3">
                <input type="text" name="query" value="{{ query }}" class="form-control"
                       placeholder="Buscar maquinaria por descripción..." id="idInputSearch"
                       aria-describedby="basic-addon2"/>
                <button type="submit" class="btn btn-primary mr-1" id="idSearchSp">Buscar</button>
            </div>
        </form>
    {% endblock %}

    <table class="container table table-responsive">
        <thead>
        <tr>
            <th> Descripcion</th>
            <th> Cantidad</th>
            <th> Precio unitario</th>
            <th> Fecha de la compra</th>
            <th> Disponibilidad</th>
            <th> Acciones</th>

        </tr>
        </thead>
        <tbody>
        {% for objects, estado in estado_guardado %}
            <tr>
                <td> {{ objects.Descripcion }}   </td>
                <td> {{ objects.Cantidad }}   </td>
                <td> {{ objects.precio_maquinaria }}   </td>
                <td> {{ objects.fecha_compra_maquinaria }}   </td>
                <td>

                    {% if estado == "Bajo Mantenimiento" %}
                        <p> Bajo Mantenimiento </p>
                    {% else %}
                        <p> Disponible </p>
                    {% endif %}
                </td>
                <td>
                    <div class="btn-accion">
                        <div>
                            <a class="text-decoration-none" href="{% url 'maquinaria:editar_maquinaria' objects.id %}">
                                <i class="ri-edit-2-line text-dark"></i>
                            </a>
                        </div>
                        <div>
                            <a class="text-decoration-none"
                               href="{% url 'maquinaria:eliminar_maquinaria' objects.id %}">
                                <i class="ri-eraser-line text-dark"></i>
                            </a>
                        </div>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>

    </table>
    <div class="mt-0">
        <a href="{% url 'maquinaria:crear_maquinaria' %}" class="btn btn-success btn-lg mt-md-5 me-md-auto ms-md-3">
            Añadir Maquinaria
        </a>
    </div>

{% endblock %}

modulos/maquinaria/templates/maquinaria/editar_maquinaria.html
{% extends 'formulario_plantilla.html' %}
{% load static %}
{% block title %}
    <title> Edición de Clientes </title>
{% endblock %}

{% block formulario %}
    {% if form.errors %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>Error al Grabar</strong> {{ form.errors }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}

    {{ form.as_p }}

{% endblock %}

modulos/maquinaria/templates/maquinaria/eliminar_maquinaria.html
{% extends 'formulario_plantilla.html' %}
{% load static %}

{% block title %}
    <title> Eliminación de Maquinaria </title>
{% endblock %}

{% block formulario %}
    {% csrf_token %}
    <h3 style='text-align: center'>¿Estás seguro de eliminar la máquina llamada: "{{ object }}"?</h3>
{% endblock %}