Gym_System-main/ecommerse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from ecommerse import settings

urlpatterns = [
    path('clientes/', include('modulos.clientes.urls')),
    path('mensualidad/', include('modulos.mensualidad.urls')),
    path('maquinaria/', include('modulos.maquinaria.urls')),
    path('instrumentos/', include('modulos.instrumentos.urls')),
    path('finanzas/', include('modulos.finanzas.urls')),
    path('', include('modulos.login.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Gym_System-main/modulos/finanzas/urls.py
from django.urls import path
from modulos.finanzas.views.finanzas.views import *


app_name = "finanzas"
urlpatterns = [
    path('detalle_finanzas/', (DetalleFinanzas.as_view()), name='detalle_finanzas'),
    path('crear_finanzas/', (RellenarFinanza.as_view()), name='crear_finanzas'),
    path('editar_finanzas/<int:pk>', (EditarFinanzas.as_view()), name='editar_finanzas'),
    path('eliminar_finanzas/<int:pk>', (EliminarFinanzas.as_view()), name='eliminar_finanzas'),

]

ecommerse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from ecommerse import settings

urlpatterns = [
    path('clientes/', include('modulos.clientes.urls')),
    path('mensualidad/', include('modulos.mensualidad.urls')),
    path('maquinaria/', include('modulos.maquinaria.urls')),
    path('instrumentos/', include('modulos.instrumentos.urls')),
    path('finanzas/', include('modulos.finanzas.urls')),
    path('', include('modulos.login.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

modulos/finanzas/urls.py
from django.urls import path
from modulos.finanzas.views.finanzas.views import *


app_name = "finanzas"
urlpatterns = [
    path('detalle_finanzas/', (DetalleFinanzas.as_view()), name='detalle_finanzas'),
    path('crear_finanzas/', (RellenarFinanza.as_view()), name='crear_finanzas'),
    path('editar_finanzas/<int:pk>', (EditarFinanzas.as_view()), name='editar_finanzas'),
    path('eliminar_finanzas/<int:pk>', (EliminarFinanzas.as_view()), name='eliminar_finanzas'),

]

Gym_System-main/modulos/finanzas/models.py
from django.db import models

from modulos.clientes.models import Cliente
# Create your models here.

class Finanzas (models.Model):

    anio = models.CharField(max_length=4)
    mes = models.CharField(max_length=2)
    mensualidades = models.IntegerField(default=None)
    ingresos = models.IntegerField(default=None)
    gastos = models.IntegerField(default=None)
    ganancias = models.IntegerField(default=None)

modulos/finanzas/models.py
from django.db import models

from modulos.clientes.models import Cliente
# Create your models here.

class Finanzas (models.Model):

    anio = models.CharField(max_length=4)
    mes = models.CharField(max_length=2)
    mensualidades = models.IntegerField(default=None)
    ingresos = models.IntegerField(default=None)
    gastos = models.IntegerField(default=None)
    ganancias = models.IntegerField(default=None)

Gym_System-main/modulos/finanzas/forms.py
from django.db import models
from django import forms
from django.utils import timezone
from django.forms import ModelForm

from modulos.finanzas.models import *


class FormFinanzas(ModelForm):
    class Meta:
        model = Finanzas
        fields = '__all__'
        widgets = {
            'personasIngresadas': forms.NumberInput(attrs={'class': 'form-control', 'id': 'personasIngresadas'}),
            'mensualidades': forms.NumberInput(
                attrs={'class': 'form-control', 'id': 'mensualidades', 'disabled': 'True'}),
            'ingresos': forms.NumberInput(attrs={'class': 'form-control', 'id': 'ingresos', 'disabled': 'True'}),
            'gastos': forms.NumberInput(attrs={'class': 'form-control', 'id': 'gastos', 'disabled': 'True'}),
            'ganancias': forms.NumberInput(attrs={'class': 'form-control', 'id': 'ganancias', 'disabled': 'True'}),
        }

modulos/finanzas/forms.py
from django.db import models
from django import forms
from django.utils import timezone
from django.forms import ModelForm

from modulos.finanzas.models import *


class FormFinanzas(ModelForm):
    class Meta:
        model = Finanzas
        fields = '__all__'
        widgets = {
            'personasIngresadas': forms.NumberInput(attrs={'class': 'form-control', 'id': 'personasIngresadas'}),
            'mensualidades': forms.NumberInput(
                attrs={'class': 'form-control', 'id': 'mensualidades', 'disabled': 'True'}),
            'ingresos': forms.NumberInput(attrs={'class': 'form-control', 'id': 'ingresos', 'disabled': 'True'}),
            'gastos': forms.NumberInput(attrs={'class': 'form-control', 'id': 'gastos', 'disabled': 'True'}),
            'ganancias': forms.NumberInput(attrs={'class': 'form-control', 'id': 'ganancias', 'disabled': 'True'}),
        }

Gym_System-main/modulos/finanzas/views/finanzas/views.py
import json

from django.db import transaction
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views.generic import *
from modulos.finanzas.models import *
from modulos.finanzas.forms import *
from modulos.mensualidad.models import *
from modulos.maquinaria.models import *
from modulos.instrumentos.models import *
from django.contrib.auth.mixins import LoginRequiredMixin

class DetalleFinanzas(LoginRequiredMixin, ListView):
    template_name = 'finanzas/detalle_finanzas.html'
    context_object_name = 'Finanzs'
    model = Finanzas
    paginate_by = 5

    def get_queryset(self):
        query = self.request.GET.get("query")
        print(query)
        if query:
            return self.model.objects.filter(anio__icontains=query) \
                or self.model.objects.filter(mes__icontains=query)
        else:
            return self.model.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Registro de Finanzas'

        return context


class RellenarFinanza(LoginRequiredMixin, CreateView):
    model = Finanzas
    template_name = 'finanzas/añadir_registro_finanzas.html'
    form_class = FormFinanzas
    success_url = reverse_lazy("finanzas:detalle_finanzas")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Añadir Registro de Finanzas'
        context['action_save'] = self.request.path
        context['url_anterior'] = '/finanzas/detalle_finanzas/'
        context['fecha'] = self.request.GET.get("fecha") or ""
        context['mensualidades'] = json.dumps(self.Mensualidad_dict())
        context['maquinaria'] = json.dumps(self.Maquinaria_dict())
        context['instrumento'] = json.dumps(self.Instrumento_dict())
        context['action'] = "add"
        # bandera para validar una agregación de registro
        return context

    def Mensualidad_dict(self):
        listado = []
        mensu = Mensualidad.objects.all()

        for i in mensu:
            items = {}
            items['cliente'] = str(i.cliente)
            items['precio'] = str(i.precio)
            items['fecha_inicio'] = str(i.fecha_inicio)
            items['fecha_finalizacion'] = str(i.fecha_finalizacion)

            listado.append(items)

        return listado

    def Maquinaria_dict(self):
        listado = []
        maquina = Maquinaria.objects.all()

        for i in maquina:
            items = {}
            items['Cantidad'] = str(i.Cantidad)
            items['precio'] = str(i.precio_maquinaria)
            items['fecha'] = str(i.fecha_compra_maquinaria)

            listado.append(items)

        return listado

    def Instrumento_dict(self):
        listado = []
        instru = Instrumento.objects.all()

        for i in instru:
            items = {}
            items['Cantidad'] = str(i.cantidad)
            items['precio'] = str(i.precio_instrumento)
            items['fecha'] = str(i.fecha_compra_instrumento)

            listado.append(items)

        return listado

    def post(self, request, *args, **kwargs):
        resp = {}
        try:
            data = json.loads(request.body)
            if data['action'] == 'add':

                with transaction.atomic():
                    registro_finanzas = Finanzas()
                    registro_finanzas.anio = data['anio']
                    registro_finanzas.mes = data['mes']
                    registro_finanzas.mensualidades = int(data['mensualidades'])
                    registro_finanzas.ingresos = float(data['ingresos'])
                    registro_finanzas.gastos = float(data['gastos'])
                    registro_finanzas.ganancias = float(data['ganancias'])
                    registro_finanzas.save()
                    print("hola")
                    resp["grabar"] = "ok"
            else:
                pass
        except Exception as e:
            resp["grabar"] = str(e)
            print(e)

        return JsonResponse(resp, safe="false")


class EditarFinanzas(LoginRequiredMixin, UpdateView):
    model = Finanzas
    template_name = 'finanzas/editar_registro_finanzas.html'
    success_url = reverse_lazy("clientes:detalle_cliente")
    form_class = FormFinanzas

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action_save'] = f"/finanzas/editar_finanzas/{self.get_object().id}"
        context['titulo'] = 'Edición de Finanzas'
        context['url_anterior'] = '/finanzas/detalle_finanzas'
        context['mensualidades'] = json.dumps(self.Mensualidad_dict())
        context['maquinaria'] = json.dumps(self.Maquinaria_dict())
        context['instrumento'] = json.dumps(self.Instrumento_dict())
        context['detalle_finanzas'] = json.dumps(self.get_detalleFinanzas())
        context['action'] = 'edit'
        return context

    def Mensualidad_dict(self):
        listado = []
        mensu = Mensualidad.objects.all()

        for i in mensu:
            items = {}
            items['cliente'] = str(i.cliente)
            items['precio'] = str(i.precio)
            items['fecha_inicio'] = str(i.fecha_inicio)
            items['fecha_finalizacion'] = str(i.fecha_finalizacion)

            listado.append(items)

        return listado

    def Maquinaria_dict(self):
        listado = []
        maquina = Maquinaria.objects.all()

        for i in maquina:
            items = {}
            items['Cantidad'] = str(i.Cantidad)
            items['precio'] = str(i.precio_maquinaria)
            items['fecha'] = str(i.fecha_compra_maquinaria)

            listado.append(items)

        return listado

    def Instrumento_dict(self):
        listado = []
        instru = Instrumento.objects.all()

        for i in instru:
            items = {}
            items['Cantidad'] = str(i.cantidad)
            items['precio'] = str(i.precio_instrumento)
            items['fecha'] = str(i.fecha_compra_instrumento)

            listado.append(items)

        return listado

    def post(self, request, *args, **kwargs):
        resp = {}
        try:
            data = json.loads(request.body)
            if data['action'] == 'edit':
                with transaction.atomic():
                    registro_finanzas = self.get_object()
                    print(registro_finanzas)
                    registro_finanzas.anio = data['anio']
                    registro_finanzas.mes = data['mes']
                    registro_finanzas.mensualidades = int(data['mensualidades'])
                    registro_finanzas.ingresos = float(data['ingresos'])
                    registro_finanzas.gastos = float(data['gastos'])
                    registro_finanzas.ganancias = float(data['ganancias'])
                    registro_finanzas.save()
                    resp["grabar"] = "ok"

            else:
                pass
        except Exception as e:
            resp["grabar"] = str(e)
            print(e)

        return JsonResponse(resp, safe="false")

    def get_detalleFinanzas(self):
        detalle = Finanzas.objects.filter(id=self.get_object().id).values()[0]
        items = {}
        items['anio'] = detalle["anio"]
        items['mes'] = detalle["mes"]
        items['mensualidades'] = str(detalle["mensualidades"])
        items['ingresos'] = str(detalle["ingresos"])
        items['gastos'] = str(detalle["gastos"])
        items['ganancias'] = str(detalle["ganancias"])
        print(items)
        return detalle


class EliminarFinanzas(LoginRequiredMixin, DeleteView):
    model = Finanzas
    template_name = 'finanzas/eliminar_registro_finanzas.html'
    success_url = reverse_lazy("finanzas:detalle_finanzas")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action_save'] = self.request.path
        context['titulo'] = 'Eliminar Registro de Finanzas'
        context['url_anterior'] = '/finanzas/detalle_finanzas'
        context['listar_url'] = '/finanzas/detalle_finanzas'

        return context

modulos/finanzas/templates/finanzas/añadir_registro_finanzas.html
{% extends 'formulario_plantilla.html' %}
{% load static %}
{% block java %}
{% endblock %}


{% block title %}
    <title> Registro de Finanzas </title>
{% endblock %}


{% block formulario %}
    {% if form.errors %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>Error al Grabar</strong> {{ form.errors }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}

    <input type="hidden" name="action" value="{{ action }}">

    <div class="form-group">
        <label class="h6">Fecha</label>
        <input type="month" class="form-control" id="fecha_año_mes">
    </div>

    <table class="table table-bordered" id="data">
        <thead>
        <tr>
            <th>Nombre</th>
            <th>Fecha de Inicio</th>
        </tr>
        </thead>
        <tbody class="table table-bordered" id="detalle">

        </tbody>

    </table>
    <div class="form-group">
        <label class="h6">Mensualidades</label>
        {{ form.mensualidades }}
    </div>
    <div class="form-group">
        <label class="h6">Ingresos </label>
        {{ form.ingresos }}
    </div>
    <div class="form-group">
        <label class="h6">Gastos</label>
        {{ form.gastos }}
    </div>
    <div class="form-group">
        <label class="h6">Ganancias</label>
        {{ form.ganancias }}
    </div>


{% endblock %}
{% block js %}
    <script src= {% static "js/peticiones.js" %}></script>
    <script type="text/javascript">

        var mensualidad =
        {{  mensualidades|safe }}
        var maquinaria =
        {{  maquinaria|safe }}
        var instrumento =
        {{  instrumento|safe }}

        var save = '{{ action_save }}'

    </script>

{% endblock %}

modulos/finanzas/templates/finanzas/detalle_finanzas.html
{% extends 'barlateral_mod_plantilla.html' %}
{% load static %}
{% block title %}
    <title> Finanzas </title>
{% endblock %}

{% block contenido %}
    {% block search %}
        <form action="{% url 'finanzas:detalle_finanzas' %}" method="GET">
            <div class="input-group mb-3">
                <input type="text" name="query" value="{{ query }}" class="form-control"
                       placeholder="Buscar registros por mes/año" id="idInputSearch" aria-describedby="basic-addon2"/>
                <button type="submit" class="btn btn-primary mr-1" id="idSearchSp">Buscar</button>
            </div>
        </form>
    {% endblock %}

    <table class="container table table-responsive">
        <thead>
        <tr>
            <th> Año</th>
            <th> Mes</th>
            <th> Mensualidades</th>
            <th> Ingresos</th>
            <th> Gastos</th>
            <th> Ganancias</th>
            <th> Acciones</th>
        </tr>
        </thead>
        <tbody>
        {% for objects in Finanzs %}
            <tr>
                <td> {{ objects.anio }}   </td>
                <td> {{ objects.mes }}   </td>
                <td> {{ objects.mensualidades }}   </td>
                <td> {{ objects.ingresos }}   </td>
                <td> {{ objects.gastos }}   </td>
                <td> {{ objects.ganancias }}   </td>
                <td>
                    <div class="btn-accion">
                        <div>
                            <a class="text-decoration-none" href="{% url 'finanzas:editar_finanzas' objects.id %}">
                                <i class="ri-refresh-line text-dark"></i>
                            </a>
                        </div>
                        <div>
                            <a class="text-decoration-none" href="{% url 'finanzas:eliminar_finanzas' objects.id %}">
                                <i class="ri-eraser-line text-dark"></i>
                            </a>
                        </div>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>

    </table>

    <div class="btn-add">
        <a href="{% url 'finanzas:crear_finanzas' %}" class="btn btn-success btn-lg mt-md-5 me-md-auto ms-md-3">
            Añadir Registro de Finanzas
        </a>
    </div>


{% endblock %}

modulos/finanzas/templates/finanzas/editar_registro_finanzas.html
{% extends 'formulario_plantilla.html' %}
{% load static %}
{% block title %}
    <title> Edición de Finanzas </title>
{% endblock %}

{% block formulario %}
    {% if form.errors %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>Error al Grabar</strong> {{ form.errors }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}

    <input type="hidden" name="action" value="{{ action }}">

    <div class="form-group">
        <label class="h6">Fecha</label>
        <input type="month" class="form-control" id="fecha_año_mes">
    </div>

    <table class="table table-bordered" id="data">
        <thead>
        <tr>
            <th>Nombre</th>
            <th>Fecha de Inicio</th>
        </tr>
        </thead>
        <tbody id="detalle">
        </tbody>
    </table>

    <div class="form-group">
        <label class="h6">Mensualidades</label>
        {{ form.mensualidades }}
    </div>
    <div class="form-group">
        <label class="h6">Ingresos </label>
        {{ form.ingresos }}
    </div>
    <div class="form-group">
        <label class="h6">Gastos</label>
        {{ form.gastos }}
    </div>
    <div class="form-group">
        <label class="h6">Ganancias</label>
        {{ form.ganancias }}
    </div>

{% endblock %}

{% block js %}
    <script src= {% static "js/peticiones.js" %}></script>
    <script type="text/javascript">

        var mensualidad =
        {{  mensualidades|safe }}
        var maquinaria =
        {{  maquinaria|safe }}
        var instrumento =
        {{  instrumento|safe }}
        var editar_finanzas =
        {{ detalle_finanzas|safe }}

        var save = '{{ action_save }}'

    </script>
{% endblock %}

modulos/finanzas/templates/finanzas/eliminar_registro_finanzas.html
{% extends 'formulario_plantilla.html' %}
{% load static %}
{% block title %}
    <title> Eliminación de Finanzas </title>
{% endblock %}

{% block formulario %}
    {% csrf_token %}
    <h3 style='text-align: center'>¿Estás seguro de eliminar este registro?</h3>
{% endblock %}